---
title: "FAQ Laboratorio di statistica"
output: 
        github_document:
                toc: TRUE
                # toc_depth: 3 # default = 3
                # fig_width: 7 # default = 7
                # fig_height: 5 # default = 5
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
```

## Come ottenere i crediti:

#### È obbligatorio frequentare il corso?

Sì, si chiama frequenza proficua per un motivo. È obbligatorio seguire almeno l'80% delle lezioni.

#### Si possono recuperare le lezioni perse?

Sì, direi di sì, *magari* a gruppi, *magari* non un mese dopo.

#### Quante sono le ore di corso?

Sono 24 ore di laboratorio e 47 di studio individuale.

#### Si svolgeranno delle prove intermedie durante il corso?

Ci saranno piccoli incarichi di lezione in lezione, e verranno portati avanti progetti individuali o di gruppo durante il corso, ma nessuna prova formale.

#### In cosa consisterà la prova finale esattamente?

Essendo il primo anno il formato della prova finale non è _esattamente_ definito.  
L'idea è di farvi utilizzare in un'analisi organica tutti i piccoli compiti che vi vengono assegnati durante il corso.


## Domande tecniche:

#### L'installazione di GIT per Windows sconsiglia di usare VIM come editor di default, che faccio?

Non ho consigli specifici, se qualcuno ne ha è il benvenuto, ma penso che provate le nuve GUI che installerete (io ho consigliato GitHub Desktop, ma non è l'unica), userete solo quelle per gestire il vostro GIT.

#### Come si crea una **pull request**

Il punto di chiedervelo prima di spiegarvelo è di imparare a cercare le risposte sul web.  
La raccomandazione è cercare in inglese.

#### Dove posso trovare i tutorial per l'utilizzo di GitHub? (_GitHub for dummies_)

#### Che differenza c'è tra Branch e Fork?

* Fork è una copia di una _repository_, contiene **tutte** le branches della repository originale.
* Branch è una copia della _master branch_, fatta per poter lavorare senza incasinare il lavoro degli altri.

#### Come si crea una pull request da GitHub Dekstop

Non si può: il comando _Create pull request_ dalla branch nella **propria fork**, reindirizza alla pagina giusta sul browser.

## Altre domande:

#### Finito il corso, possiamo trovare sul web qualche valido tutorial per migliorare le proprie capacità nell'uso di R? Ne consigliereste qualcuno in particolare?

Insieme al materiale delle lezioni verrà fornito anche il materiale di approfondimanto, la community di R è estremamente vivace, e il miglior modo di entrare nel vivo della materia è quello di seguirne gli attori principali. Seguire i collegamenti nel materiale allegato dovrebbe portare a quasi tutte le persone giuste.

---

<div align="center">
[Syllabus](../README.md)
</div>
---

