---
title: "Laboratorio di Statistica Forestale"
# author: "Giovanni Iacopetti"
# date: "30/1/2018"
output: 
        github_document:
                toc: TRUE
                # toc_depth: 3 # default = 3
                # fig_width: 7 # default = 7
                # fig_height: 5 # default = 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

* Docente: Luisa Ghelardini
* Assistenza: Martina Pollastrini, Giovanni Iacopetti
* CFU: 3
* Ore di laboratorio: 24
* Ore di studio: 47 
* Prova finale: Scritta - senza voto
* Ricevimento:
  * un'ora, dopo la lezione in laboratorio
  * su appuntamento inviando un'email al nostro indirizzo dell'università  
    * Giovanni Iacopetti (giovanni.iacopetti)
    
* **Si consiglia _vivamente_ di utilizzare il proprio portatile**

---

## Descrizione del corso:

Il corso è un corso fortemente applicativo, dedicato a tutti gli studenti della Scuola di Agraria, con poca o nulla esperienza nel campo della programmazione e dell'analisi dei dati.
Il corso ruoterà attorno ai nuovi standard di immagazzinamento, gestione e analisi dei dati, con un occhio di riguardo per gli elementi di statistica che vi sono sottesi.
Il tutto mantenendosi concentrati sulle reali applicazioni delle conoscenze acquisite.
Al termine del corso gli studenti saranno in grado di impostare, sviluppare e finalizzare un'analisi dei dati **chiara**, **verificabile**, **mantenibile** e **replicabile**.

## Obbiettivi del corso:

Alla fine del corso gli studenti saranno in grado di:

* Identificare quali dati raccogliere per utilizzare delle semplici tecniche statistiche
* Digitalizzare i dati raccolti correttamente
* Raccogliere, importare ed utilizzare dati nei più comuni formati (.csv .tsv .xlsx)
* Utilizzare programmaticamente moderni strumenti di collaborazione
* Costruire ed utilizzare elementari programmi in R per l'analisi dei dati
* Utilizzare le librerie esterne di R per risolvere specifici problemi
* Visualizzare i dati e i risultati tramite tecniche appropriate
* Generare dei report facilmente fruibili tramite Markdown
* Inserire tutto il processo in un contesto di Version Control

## Prerequisiti del corso:
Nessuno. 

Il materiale verrà trattato dall'inizio, senza dare alcunché per scontato.  
Buona parte del materiale di supporto alla lezione (e in generale all'analisi dei dati) viene redatto in inglese (anche dagli italiani), è consigliata quindi un po' di buona volontà per affrontare una nuova terminologia in inglese.

Durante il corso verranno utilizzati principalmente R, RStudio e GitHub.  
Non è *indispensabile* avere tutto installato per la prima lezione ma lo sarà per la seconda lezione, e l'ora di ricevimento al termine della prima è un buon momento per risolvere eventuali problemi.

#### Installazioni e account (in quest'ordine):
* [R](https://cran.rstudio.com): il linguaggio di programmazione che verrà utilizzato per tutto il corso
* [RStudio](https://www.rstudio.com/products/rstudio/download/): l'interfaccia grafica che permette di utilizzare R in modo molto più intuitivo
* GIT: il sistema di *version control* che renderà la vostra vita più tranquilla (alla fine) L'installazione può essere un po' complicata, per ogni problema - e per un'ottima introduzione all'argomento - consultate [Happy Git With R](http://happygitwithr.com/)
* [GitHub](http://github.com/): **N.B.** c'è un sistema di account per gli studenti che toglie alcune limitazioni degli account 'free' [a questo link](https://education.github.com/pack)
* [GitHub Desktop](https://desktop.github.com/): un software per gestire i propri progetti Git senza passare dal browser (permette di gestire anche i progetti in locale che non sono su GitHub)

## Presenze 2018

A [questo link](https://docs.google.com/spreadsheets/d/19U_JozMlFgE4YfD2kzcpR5lROR4U_wjfKJ3RsSGnqzk/edit?usp=sharing) è possibilie controllare il registro delle presenze. Chi è segnato senza l'anno di corso è pregato di mandarmelo per e-mail, in modo da poter aggiungere anche il suo indirizzo alla mailing-list.

## Lezioni

| Data       | Aula | Lezione                                                    |
| ---        | ---  | ---                                                        |
| 2018-03-20 |  J   | [lez01: Introduzione al corso, l'analisi dei dati, approccio alle statistiche](lez01/) |
| 2018-03-27 |  J   | [lez02: R, gli oggetti ed i tipi di variabili](lez02/) |
|            |      |                                                        |
| alla fine  | casa | [lez97: Le cose e i loro nomi](lez97/) |
| alla fine  | casa | [lez98: Le domande da fare ai tuoi dati](lez98/) |
| alla fine  | casa | [lez99: I passi da fare, per filo e per segno](lez99/) |

